
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnlckmqcchpqmgkcvofv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ubGNrbXFjY2hwcW1na2N2b2Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDA3MzYsImV4cCI6MjA2NDg3NjczNn0.dUOF0lTpbjdBZmEB3uaI539jBsmG6ooR6YCPoAdR7Fc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
